// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminsOfChannelsRequest struct {
	ID         int64
	ChatID     pgtype.Int8
	ChannelsID pgtype.Int4
	Username   pgtype.Text
	FirstName  pgtype.Text
	SecondName pgtype.Text
}

type Channel struct {
	ID   int64
	Name string
}

type ChannelsAdmin struct {
	ID         int64
	ChatID     pgtype.Int8
	ChannelsID pgtype.Int4
}

type SubscriptionToChannel struct {
	ID         int64
	ChatID     pgtype.Int8
	ChannelsID pgtype.Int4
	Username   pgtype.Text
	Title      pgtype.Text
	ChatType   pgtype.Text
}
