name: SSH deploy on push in main
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '21.6.2'
      - run: cd client && npm install && npm run build

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22.0'
      - run: cd server && go build -o server_bin
      
      - name: rsync deploy client build
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avz --exclude '.git' --exclude '.github' --exclude '.gitignore'
          path: client/build
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: root
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_path: ${{ secrets.REMOTE_PATH }}

      - name: rsync deploy server build
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avz --exclude '.git' --exclude '.github' --exclude '.gitignore'
          path: server/server_bin
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: root
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_path: ${{ secrets.REMOTE_PATH }}

      - name: setup client to web server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          key: ${{ secrets.REMOTE_KEY }}
          port: 22
          script: |
            rm -rf /var/www/html/platforma_bot_admin/*
            cp -r github_action_deployments/platforma_bot/build/* /var/www/html/platforma_bot_admin/
      
      - name: setup server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          key: ${{ secrets.REMOTE_KEY }}
          port: 22
          script: |
            systemctl stop pbserver.service
            rm /var/www/pbserver/server_bin
            cp github_action_deployments/platforma_bot/server_bin /var/www/pbserver/server_bin
            systemctl start pbserver.service
          
